// ============================================================
// Dummy Animals for Animal Shelter (MongoDB)
// Database: animal_registry, Collection: animals
// Run: mongosh animal_registry 02-animals.js
// ============================================================

// User references (match 01-users.sql)
const ADMIN_ID   = "a1b2c3d4-0001-4000-8000-000000000001";
const JELENA_ID  = "a1b2c3d4-0002-4000-8000-000000000002";
const NIKOLA_ID  = "a1b2c3d4-0003-4000-8000-000000000003";

const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000);

db.animals.deleteMany({});

const animals = [
  // === 10 RODENTS (Beavers, Nutrias, Capybaras) ===
  {
    _id: ObjectId("66a000000000000000000001"),
    name: "Boris",
    category: "Rodent",
    breed: "European Beaver",
    gender: "Male",
    ageMonths: 36,
    weight: 22.5,
    color: "Dark Brown",
    chipId: "ROD-BVR-001",
    status: "Active",
    description: "Large European beaver, very active swimmer. Found near river Danube with injured tail.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(60), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted to shelter" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60)
  },
  {
    _id: ObjectId("66a000000000000000000002"),
    name: "Bella",
    category: "Rodent",
    breed: "European Beaver",
    gender: "Female",
    ageMonths: 24,
    weight: 18.0,
    color: "Light Brown",
    chipId: "ROD-BVR-002",
    status: "Active",
    description: "Young female beaver, pair with Boris. Calm temperament.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(55), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted to shelter" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(55)
  },
  {
    _id: ObjectId("66a000000000000000000003"),
    name: "Nutty",
    category: "Rodent",
    breed: "Nutria",
    gender: "Male",
    ageMonths: 18,
    weight: 7.5,
    color: "Brown",
    chipId: "ROD-NTR-001",
    status: "Active",
    description: "Friendly nutria rescued from urban canal. Loves vegetables.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(45), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Rescued from canal" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45)
  },
  {
    _id: ObjectId("66a000000000000000000004"),
    name: "Nala",
    category: "Rodent",
    breed: "Nutria",
    gender: "Female",
    ageMonths: 12,
    weight: 6.0,
    color: "Dark Brown",
    chipId: "ROD-NTR-002",
    status: "MedicalCare",
    description: "Young nutria with skin condition, under veterinary treatment.",
    imagePaths: [],
    statusHistory: [
      { status: "Active", changedAt: daysAgo(40), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted" },
      { status: "MedicalCare", changedAt: daysAgo(10), changedBy: NIKOLA_ID, changedByUsername: "dr_nikola", note: "Skin condition detected" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10)
  },
  {
    _id: ObjectId("66a000000000000000000005"),
    name: "Carlos",
    category: "Rodent",
    breed: "Capybara",
    gender: "Male",
    ageMonths: 48,
    weight: 55.0,
    color: "Reddish Brown",
    chipId: "ROD-CPB-001",
    status: "Active",
    description: "Largest rodent in the shelter. Very social and gentle. Loves watermelon.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(90), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Transferred from zoo" }],
    registeredBy: ADMIN_ID,
    registeredByUsername: "admin",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90)
  },
  {
    _id: ObjectId("66a000000000000000000006"),
    name: "Coco",
    category: "Rodent",
    breed: "Capybara",
    gender: "Female",
    ageMonths: 36,
    weight: 48.0,
    color: "Brown",
    chipId: "ROD-CPB-002",
    status: "Active",
    description: "Calm capybara, enjoys sunbathing. Companion of Carlos.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(85), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Transferred from zoo" }],
    registeredBy: ADMIN_ID,
    registeredByUsername: "admin",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(85)
  },
  {
    _id: ObjectId("66a000000000000000000007"),
    name: "Peanut",
    category: "Rodent",
    breed: "Capybara",
    gender: "Male",
    ageMonths: 12,
    weight: 35.0,
    color: "Golden Brown",
    chipId: "ROD-CPB-003",
    status: "Quarantine",
    description: "Young capybara, recently arrived. In quarantine for observation.",
    imagePaths: [],
    statusHistory: [
      { status: "Quarantine", changedAt: daysAgo(7), changedBy: NIKOLA_ID, changedByUsername: "dr_nikola", note: "New arrival, quarantine protocol" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7)
  },
  {
    _id: ObjectId("66a000000000000000000008"),
    name: "Nugget",
    category: "Rodent",
    breed: "Nutria",
    gender: "Male",
    ageMonths: 30,
    weight: 8.2,
    color: "Brown",
    chipId: "ROD-NTR-003",
    status: "Adopted",
    description: "Friendly nutria, successfully adopted by wildlife sanctuary.",
    imagePaths: [],
    statusHistory: [
      { status: "Active", changedAt: daysAgo(70), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted" },
      { status: "Adopted", changedAt: daysAgo(15), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Adopted by local wildlife sanctuary" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(15)
  },
  {
    _id: ObjectId("66a000000000000000000009"),
    name: "Willow",
    category: "Rodent",
    breed: "European Beaver",
    gender: "Female",
    ageMonths: 8,
    weight: 12.0,
    color: "Brown",
    chipId: "ROD-BVR-003",
    status: "Active",
    description: "Young beaver kit, found orphaned. Growing well.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(30), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Orphan kit admitted" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30)
  },
  {
    _id: ObjectId("66a00000000000000000000a"),
    name: "Chestnut",
    category: "Rodent",
    breed: "Capybara",
    gender: "Female",
    ageMonths: 24,
    weight: 42.0,
    color: "Dark Brown",
    chipId: "ROD-CPB-004",
    status: "Active",
    description: "Mid-sized capybara, very curious and playful.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(50), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted to shelter" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(50)
  },

  // === 5 DOGS ===
  {
    _id: ObjectId("66a00000000000000000000b"),
    name: "Rex",
    category: "Dog",
    breed: "German Shepherd",
    gender: "Male",
    ageMonths: 36,
    weight: 34.0,
    color: "Black and Tan",
    chipId: "DOG-GS-001",
    status: "Active",
    description: "Energetic German Shepherd, good with other dogs. Needs daily exercise.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(45), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Surrendered by owner" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45)
  },
  {
    _id: ObjectId("66a00000000000000000000c"),
    name: "Luna",
    category: "Dog",
    breed: "Labrador Retriever",
    gender: "Female",
    ageMonths: 24,
    weight: 28.0,
    color: "Golden",
    chipId: "DOG-LR-001",
    status: "Active",
    description: "Sweet Labrador, loves fetch and swimming. Great family dog.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(35), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Found stray" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(35)
  },
  {
    _id: ObjectId("66a00000000000000000000d"),
    name: "Max",
    category: "Dog",
    breed: "Beagle",
    gender: "Male",
    ageMonths: 18,
    weight: 12.5,
    color: "Tricolor",
    chipId: "DOG-BGL-001",
    status: "MedicalCare",
    description: "Young beagle with ear infection, under treatment.",
    imagePaths: [],
    statusHistory: [
      { status: "Active", changedAt: daysAgo(25), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted" },
      { status: "MedicalCare", changedAt: daysAgo(5), changedBy: NIKOLA_ID, changedByUsername: "dr_nikola", note: "Ear infection diagnosed" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(5)
  },
  {
    _id: ObjectId("66a00000000000000000000e"),
    name: "Daisy",
    category: "Dog",
    breed: "Mixed Breed",
    gender: "Female",
    ageMonths: 60,
    weight: 22.0,
    color: "White and Brown",
    chipId: "DOG-MIX-001",
    status: "Adopted",
    description: "Gentle older dog, adopted by loving family.",
    imagePaths: [],
    statusHistory: [
      { status: "Active", changedAt: daysAgo(80), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Surrendered by owner" },
      { status: "Adopted", changedAt: daysAgo(20), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Adopted by Petrovic family" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(20)
  },
  {
    _id: ObjectId("66a00000000000000000000f"),
    name: "Rocky",
    category: "Dog",
    breed: "Husky",
    gender: "Male",
    ageMonths: 30,
    weight: 25.0,
    color: "Gray and White",
    chipId: "DOG-HSK-001",
    status: "Active",
    description: "Energetic husky, loves running. Needs experienced owner.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(40), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Transferred from another shelter" }],
    registeredBy: ADMIN_ID,
    registeredByUsername: "admin",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(40)
  },

  // === 5 CATS ===
  {
    _id: ObjectId("66a000000000000000000010"),
    name: "Mika",
    category: "Cat",
    breed: "Persian",
    gender: "Female",
    ageMonths: 48,
    weight: 4.5,
    color: "White",
    chipId: "CAT-PRS-001",
    status: "Active",
    description: "Beautiful Persian cat, very affectionate. Indoor cat.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(50), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Surrendered by owner" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(50)
  },
  {
    _id: ObjectId("66a000000000000000000011"),
    name: "Shadow",
    category: "Cat",
    breed: "Domestic Shorthair",
    gender: "Male",
    ageMonths: 12,
    weight: 3.8,
    color: "Black",
    chipId: "CAT-DSH-001",
    status: "Active",
    description: "Playful young cat, good mouser. Gets along with other cats.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(28), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Found stray" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28)
  },
  {
    _id: ObjectId("66a000000000000000000012"),
    name: "Ginger",
    category: "Cat",
    breed: "Maine Coon",
    gender: "Female",
    ageMonths: 36,
    weight: 6.2,
    color: "Orange Tabby",
    chipId: "CAT-MCN-001",
    status: "Quarantine",
    description: "Large Maine Coon, in quarantine after being found outdoors.",
    imagePaths: [],
    statusHistory: [
      { status: "Quarantine", changedAt: daysAgo(5), changedBy: NIKOLA_ID, changedByUsername: "dr_nikola", note: "New arrival quarantine" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5)
  },
  {
    _id: ObjectId("66a000000000000000000013"),
    name: "Whiskers",
    category: "Cat",
    breed: "Siamese",
    gender: "Male",
    ageMonths: 24,
    weight: 4.0,
    color: "Cream and Brown",
    chipId: "CAT-SIA-001",
    status: "Active",
    description: "Vocal Siamese, very social. Loves attention.",
    imagePaths: [],
    statusHistory: [{ status: "Active", changedAt: daysAgo(35), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Surrendered by owner" }],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(35)
  },
  {
    _id: ObjectId("66a000000000000000000014"),
    name: "Cleo",
    category: "Cat",
    breed: "British Shorthair",
    gender: "Female",
    ageMonths: 72,
    weight: 5.0,
    color: "Blue Gray",
    chipId: "CAT-BSH-001",
    status: "Adopted",
    description: "Senior cat, calm and gentle. Found her forever home.",
    imagePaths: [],
    statusHistory: [
      { status: "Active", changedAt: daysAgo(65), changedBy: JELENA_ID, changedByUsername: "jelena_care", note: "Admitted" },
      { status: "Adopted", changedAt: daysAgo(10), changedBy: ADMIN_ID, changedByUsername: "admin", note: "Adopted by elderly couple" }
    ],
    registeredBy: JELENA_ID,
    registeredByUsername: "jelena_care",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(10)
  }
];

db.animals.insertMany(animals);
print("Inserted " + animals.length + " animals");
